Data frames are most commonly used pandas object.Its like a spreadsheet or a SQL talbe

In [7]:
import pandas as pa

In [13]:
#dataf= pa.read_csv('pokemon_data.csv')
dataf= pa.read_excel('pokemon_data.xlsx')

In [15]:
print (dataf.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [18]:
dataf= pa.read_csv('pokemon_data.txt',delimiter='\t')

In [19]:
print(dataf.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [38]:
#read Headers
#print(dataf.columns)
#read secific columns
#print(dataf[['Name','Speed']])
#read rows
#print(dataf.iloc[1])
#print(dataf.iloc[0:4]) # print 0 to 4
#read to specific cell with row num and col num
print(dataf.iloc[1,3])

Poison

In [42]:
for index,row1 in dataf.iterrows():
    print(index,row1['Speed'])

0 45
1 60
2 80
3 80
4 65
5 80
6 100
7 100
8 100
9 43
10 58
11 78
12 78
13 45
14 30
15 70
16 50
17 35
18 75
19 145
20 56
21 71
22 101
23 121
24 72
25 97
26 70
27 100
28 55
29 80
30 90
31 110
32 40
33 65
34 41
35 56
36 76
37 50
38 65
39 85
40 35
41 60
42 65
43 100
44 20
45 45
46 55
47 90
48 30
49 40
50 50
51 25
52 30
53 45
54 90
55 95
56 120
57 90
58 115
59 55
60 85
61 70
62 95
63 60
64 95
65 90
66 90
67 70
68 90
69 105
70 120
71 150
72 35
73 45
74 55
75 40
76 55
77 70
78 70
79 100
80 20
81 35
82 45
83 90
84 105
85 15
86 30
87 30
88 45
89 70
90 60
91 75
92 100
93 45
94 70
95 25
96 50
97 40
98 70
99 80
100 95
101 110
102 130
103 70
104 42
105 67
106 50
107 75
108 100
109 140
110 40
111 55
112 35
113 45
114 87
115 76
116 30
117 35
118 60
119 25
120 40
121 50
122 60
123 90
124 100
125 60
126 85
127 63
128 68
129 85
130 115
131 90
132 105
133 95
134 105
135 93
136 85
137 105
138 110
139 80
140 81
141 81
142 60
143 48
144 55
145 65
146 130
147 65
148 40
149 35
150 55
151 55
152 80
153 130
154 150
155 30
156 85
157 100
158 90
159 50
160 70
161 80
162 130
163 130
164 140
165 100
166 45
167 60
168 80
169 65
170 80
171 100
172 43
173 58
174 78
175 20
176 90
177 50
178 70
179 55
180 85
181 30
182 40
183 130
184 67
185 67
186 60
187 15
188 15
189 20
190 40
191 70
192 95
193 35
194 45
195 55
196 45
197 50
198 40
199 50
200 30
201 70
202 50
203 80
204 110
205 85
206 30
207 30
208 95
209 15
210 35
211 110
212 65
213 91
214 30
215 85
216 48
217 33
218 85
219 15
220 40
221 45
222 85
223 30
224 30
225 30
226 45
227 85
228 65
229 75
230 5
231 85
232 75
233 115
234 40
235 55
236 20
237 30
238 50
239 50
240 35
241 65
242 45
243 75
244 70
245 70
246 65
247 95
248 115
249 85
250 40
251 50
252 60
253 85
254 75
255 35
256 70
257 65
258 95
259 83
260 100
261 55
262 115
263 100
264 85
265 41
266 51
267 61
268 71
269 110
270 90
271 100
272 70
273 95
274 120
275 145
276 45
277 55
278 80
279 100
280 40
281 50
282 60
283 70
284 35
285 70
286 60
287 100
288 20
289 15
290 65
291 15
292 65
293 30
294 50
295 70
296 30
297 60
298 80
299 85
300 125
301 85
302 65
303 40
304 50
305 80
306 100
307 65
308 60
309 35
310 70
311 30
312 90
313 100
314 40
315 160
316 40
317 28
318 48
319 68
320 25
321 50
322 20
323 30
324 50
325 70
326 50
327 20
328 50
329 50
330 30
331 40
332 50
333 50
334 60
335 80
336 100
337 65
338 105
339 135
340 95
341 95
342 85
343 85
344 65
345 40
346 55
347 65
348 95
349 105
350 60
351 60
352 35
353 40
354 20
355 20
356 60
357 80
358 60
359 10
360 70
361 100
362 35
363 55
364 50
365 80
366 80
367 90
368 65
369 70
370 70
371 60
372 60
373 35
374 55
375 55
376 75
377 23
378 43
379 75
380 45
381 80
382 81
383 70
384 40
385 45
386 65
387 75
388 25
389 25
390 51
391 65
392 75
393 115
394 23
395 50
396 80
397 100
398 25
399 45
400 65
401 32
402 52
403 52
404 55
405 97
406 50
407 50
408 100
409 120
410 30
411 50
412 70
413 110
414 50
415 50
416 50
417 110
418 110
419 110
420 110
421 90
422 90
423 90
424 90
425 95
426 115
427 100
428 150
429 150
430 90
431 180
432 31
433 36
434 56
435 61
436 81
437 108
438 40
439 50
440 60
441 60
442 80
443 100
444 31
445 71
446 25
447 65
448 45
449 60
450 70
451 55
452 90
453 58
454 58
455 30
456 30
457 36
458 36
459 36
460 36
461 66
462 70
463 40
464 95
465 85
466 115
467 35
468 85
469 34
470 39
471 115
472 70
473 80
474 85
475 105
476 135
477 105
478 71
479 85
480 112
481 45
482 74
483 84
484 23
485 33
486 10
487 60
488 30
489 91
490 35
491 42
492 82
493 102
494 92
495 5
496 60
497 90
498 112
499 32
500 47
501 65
502 95
503 50
504 85
505 46
506 66
507 91
508 50
509 40
510 60
511 30
512 125
513 60
514 50
515 40
516 50
517 95
518 83
519 80
520 95
521 95
522 65
523 95
524 80
525 90
526 80
527 110
528 40
529 45
530 110
531 91
532 86
533 86
534 86
535 86
536 86
537 95
538 80
539 115
540 90
541 100
542 77
543 100
544 90
545 90
546 85
547 80
548 100
549 125
550 100
551 127
552 120
553 100
554 63
555 83
556 113
557 45
558 55
559 65
560 45
561 60
562 70
563 42
564 77
565 55
566 60
567 80
568 66
569 106
570 64
571 101
572 64
573 101
574 64
575 101
576 24
577 29
578 43
579 65
580 93
581 76
582 116
583 15
584 20
585 25
586 72
587 114
588 68
589 88
590 50
591 50
592 35
593 40
594 45
595 64
596 69
597 74
598 45
599 85
600 42
601 42
602 92
603 57
604 47
605 112
606 66
607 116
608 30
609 90
610 98
611 65
612 74
613 92
614 50
615 95
616 55
617 60
618 55
619 45
620 48
621 58
622 97
623 30
624 30
625 22
626 32
627 70
628 110
629 65
630 75
631 65
632 105
633 75
634 115
635 45
636 55
637 65
638 20
639 30
640 30
641 55
642 98
643 44
644 59
645 79
646 75
647 95
648 103
649 60
650 20
651 15
652 30
653 40
654 60
655 65
656 65
657 108
658 10
659 20
660 30
661 50
662 90
663 60
664 40
665 50
666 30
667 40
668 20
669 55
670 80
671 57
672 67
673 97
674 40
675 50
676 105
677 25
678 145
679 32
680 65
681 105
682 48
683 35
684 55
685 60
686 70
687 55
688 60
689 80
690 60
691 80
692 65
693 109
694 38
695 58
696 98
697 60
698 100
699 108
700 108
701 108
702 111
703 121
704 111
705 101
706 90
707 90
708 101
709 91
710 95
711 95
712 95
713 108
714 108
715 90
716 128
717 99
718 38
719 57
720 64
721 60
722 73
723 104
724 71
725 97
726 122
727 57
728 78
729 62
730 84
731 126
732 35
733 29
734 89
735 72
736 106
737 42
738 52
739 75
740 52
741 68
742 43
743 58
744 102
745 68
746 104
747 104
748 28
749 35
750 60
751 60
752 23
753 29
754 49
755 72
756 45
757 73
758 50
759 68
760 30
761 44
762 44
763 59
764 70
765 109
766 48
767 71
768 46
769 58
770 60
771 118
772 101
773 50
774 40
775 60
776 80
777 75
778 38
779 56
780 51
781 56
782 46
783 41
784 84
785 99
786 69
787 54
788 28
789 28
790 55
791 123
792 99
793 99
794 95
795 50
796 110
797 70
798 80
799 70

In [44]:
dataf.loc[dataf['Type 1']=="Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

#Sorting/Describing Data - Tells  the means std etc

In [45]:
dataf.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

#Sorting

In [48]:
dataf.sort_values(['Type 1','HP'],ascending=True)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False

#adding to a category

In [50]:
dataf['Total'] = dataf['HP']+dataf['Attack']+dataf['Defense']

In [52]:
dataf.head()# You can see the Total Column

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,134

In [53]:
#Drop a column
dataf.drop(columns='Total')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [54]:
dataf

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,134
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,300
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,320
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,250
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,300
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,310

In [58]:
dataf['Totalnew']=dataf.iloc[:,4:9].sum(axis=1)
#sum function
#when axis is 1 it adds horizontally
#when axis is 0 it adds vertically

In [65]:
print(dataf['Total'])

0      143
1      185
2      245
3      303
4      134
      ...
795    300
796    320
797    250
798    300
799    310
Name: Total, Length: 800, dtype: int64

In [68]:
dataf.drop(columns='Total')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Totalnew
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,550
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,590
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,530
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,600
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,530

In [69]:
dataf

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Totalnew
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,134,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,300,550
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,320,590
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,250,530
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,300,600
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,310,530

In [71]:
del dataf['Total']

In [72]:
dataf

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Totalnew
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,550
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,590
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,530
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,600
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,530

#moving the colums to the right and left in the dataframe

In [73]:
cols = list(dataf.columns.values)
dataf = dataf[cols[0:4]+[cols[-1] ]+ cols[4:12]]

In [74]:
dataf

,#,Name,Type 1,Type 2,Totalnew,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,273,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,345,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,244,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,550,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,590,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,530,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,600,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,530,80,110,120,130,90,70,6,True

Saving our CSv

In [75]:
dataf.to_csv('modified.csv')